/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrameGrammers.java
 *
 * Created on Dec 5, 2014, 11:17:26 PM
 */
package MyFormPackage;

import MyTools.CheckInput;
import MyTools.Tools;
import Mydata.DataSizeClasses;
import Mydata.GrammerProperties;
import java.awt.Point;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ali
 */
public class FrameGrammers extends javax.swing.JFrame {

    /**
     * <b>selectGr:</b> is boolean value for check<br/>
     * User Selected<b> Left Grammer or Right Grammer</b>
     *
     */
    static boolean selectedGR;
    /**
     * <b>newLine</b> is const value for get line next in textarea for print Grammer
     */
    private final String newLine = "\n";
    /**
     * create ArrayList of Class GrammerProperties in Pakage Mydata
     */
    ArrayList<GrammerProperties> list = new ArrayList<GrammerProperties>();

    /** Creates new form FrameGrammers */
    public FrameGrammers(boolean select) {

        initComponents();
        jComboBoxFinal.setVisible(false);
        jbtnEndFinal.setVisible(false);
        jbtnFinal.setVisible(false);
        jtxtAlpba.setText(null);
        jtxtareaPrint.setEditable(false);
        /**
         * <b>Use pakage MyTools:</b>
         * Use Class setFormLocation for locality Frame in center Desktop
         */
        Tools.setFormLocation(this);

        selectedGR = select;
        /**
         * if user selected Grammer Left
         * change location textbox and combobox
         */
        if (selectedGR != true) {
            Point locationNewCombobox = jtxtAlpba.getLocation();
            Point locationNewTxt = jComboBoxRight.getLocation();
            int w = locationNewCombobox.x;
            int h = locationNewCombobox.y;
            jComboBoxRight.setLocation(w, h);
            w = locationNewTxt.x;
            h = locationNewTxt.y;
            jtxtAlpba.setLocation(w - 30, h);
        }

    }//end constructor

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxLeft = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jtxtAlpba = new javax.swing.JTextField();
        jComboBoxRight = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jbtnAdd = new javax.swing.JButton();
        jbtnEG1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtareaPrint = new javax.swing.JTextArea();
        jComboBoxFinal = new javax.swing.JComboBox();
        jbtnFinal = new javax.swing.JButton();
        jbtnEndFinal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("دریافت گرامر");
        setBounds(new java.awt.Rectangle(30, 40, 100, 100));
        setMinimumSize(new java.awt.Dimension(490, 600));
        getContentPane().setLayout(null);

        jComboBoxLeft.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "S", "A", "B", "C", "q0", "q1", "q2", "q3", "q4", "q5", "q6", "q7", "q8", "q9" }));
        getContentPane().add(jComboBoxLeft);
        jComboBoxLeft.setBounds(120, 50, 50, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/paykan.gif"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 50, 24, 20);

        jtxtAlpba.setText("  ");
        getContentPane().add(jtxtAlpba);
        jtxtAlpba.setBounds(210, 50, 70, 20);

        jComboBoxRight.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "S", "A", "B", "C", "q0", "q1", "q2", "q3", "q4", "q5", "q6", "q7", "q8", "q9" }));
        getContentPane().add(jComboBoxRight);
        jComboBoxRight.setBounds(290, 50, 50, 20);

        jLabel2.setText("دستورات گرامر خود را با اشیاء زیر درست کنید.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 10, 217, 28);

        jbtnAdd.setText("اضافه کن");
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnAdd);
        jbtnAdd.setBounds(240, 90, 210, 23);

        jbtnEG1.setText("اتمام گرامر");
        jbtnEG1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEG1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnEG1);
        jbtnEG1.setBounds(240, 130, 210, 23);

        jtxtareaPrint.setColumns(20);
        jtxtareaPrint.setRows(5);
        jScrollPane1.setViewportView(jtxtareaPrint);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 76, 210, 220);

        getContentPane().add(jComboBoxFinal);
        jComboBoxFinal.setBounds(240, 190, 50, 20);

        jbtnFinal.setText("اضافه کردن به حالات نهایی");
        jbtnFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFinalActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnFinal);
        jbtnFinal.setBounds(300, 190, 160, 23);

        jbtnEndFinal.setText("اتمام حالات نهایی");
        jbtnEndFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEndFinalActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnEndFinal);
        jbtnEndFinal.setBounds(240, 230, 220, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * <b>i <b>is index for array list
     *
     */
    int i = 0;

    /**
     * this butten jobs is:
     * 1:Recive data for input and save to ArrayList
     * 2:print data input in textarea
     * @param evt
     */
    /**
     * this button jobs:تک تک دستورات گرامر را به ArrayList اضافه می کند.
     * @param evt
     */
    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
        /**
         * create new interfase of class GrammerPropertis
         * in pakage MyData
         */
        GrammerProperties e = new GrammerProperties();
        /**
         * in is varible مقدار دهی می شود که رشته ورودی  جزه حروف الفبا کوچک هست یا نه؟
         */
        boolean in = true;
        MyTools.CheckInput check = new CheckInput();
        jtxtAlpba.setText(jtxtAlpba.getText().trim());
        if (jtxtAlpba.getText().length()==0) {
            JOptionPane.showMessageDialog(null, "فیلدی نباید خالی باشد", "خطا", JOptionPane.ERROR_MESSAGE);
            in = false;
        }
        if (check.CheckAlephba(jtxtAlpba.getText().toString()) == false && in) {
            JOptionPane.showMessageDialog(null, "رشته باید حروف الفبا کوچک باشد.", "خطا", JOptionPane.ERROR_MESSAGE);
            jtxtAlpba.setText(null);
            in = false;
        }
        if (jtxtAlpba.getText().toString() != null && in) {
            if (jComboBoxRight.getSelectedIndex()==0) {
                e.setRightValue("@");
            } else {
                e.setRightValue(jComboBoxRight.getSelectedItem().toString());
            }

            e.setAlephba(jtxtAlpba.getText().toString());
            e.setLeftValue(jComboBoxLeft.getSelectedItem().toString());

            /**
             * save data to ArrayList
             */
            list.add(i, e);
            /**<b>i++</b>
             * go new index of array
             */
            i++;
            /**
             * print view of Grammer for user
             */
            String Gramer;
            if (selectedGR) {
                Gramer = "   " + jComboBoxLeft.getSelectedItem().toString() +
                        "  --> " +
                        jtxtAlpba.getText().toString() +
                        jComboBoxRight.getSelectedItem().toString();
            } else {
                Gramer = "   " + jComboBoxLeft.getSelectedItem().toString() +
                        "  --> " +
                        jComboBoxRight.getSelectedItem().toString() +
                        jtxtAlpba.getText().toString();
            }

            jtxtareaPrint.append(Gramer + newLine);

            jtxtAlpba.setText(null);
        }
    }//GEN-LAST:event_jbtnAddActionPerformed
    /**
     * this button jobs is disable this form and Create new Form
     * and sent Array list list to new Frame
     * @param evt
     */
    String[] StateFinal = null;
    String[] varible = null;
    int numberOfVar = 0;

    /**
     * this button jobs:انتخاب های حالت نهایی کاربر را فراهم می کند
     * @param evt
     */
    private void jbtnEG1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEG1ActionPerformed
        jbtnAdd.setEnabled(false);
        jbtnEG1.setEnabled(false);
        jComboBoxFinal.setVisible(true);
        jbtnEndFinal.setVisible(true);
        jbtnFinal.setVisible(true);

        ArrayList<GrammerProperties> list2 = new ArrayList<GrammerProperties>(list.size());
        Mydata.DataSizeClasses a = new DataSizeClasses();

        a.copyToList(list, list2);

        numberOfVar = a.getNumberOfVarible(list2);

        varible = new String[numberOfVar];

        a.copyToList(list, list2);

        a.getResiveVarible(list2, varible);

        for (int j = 0; j < numberOfVar; j++) {
            jComboBoxFinal.insertItemAt(varible[j], j);
            varible[j] = null;
        }
    }//GEN-LAST:event_jbtnEG1ActionPerformed
    /**
     * f is counter to creare  combabox for menu for choose state final
     *
     */
    int f = 0;

    /**
     *this button jobs:حالت نهایی که توسط کاربر انتخاب می شود را در آرایه ذخیره می کند
     * @param evt
     */
    private void jbtnFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFinalActionPerformed
        // TODO add your handling code here:
        if (jComboBoxFinal.getSelectedItem().toString() != null) {
            varible[f] = jComboBoxFinal.getSelectedItem().toString();
            f++;
            jComboBoxFinal.removeItemAt(jComboBoxFinal.getSelectedIndex());
        }
    }//GEN-LAST:event_jbtnFinalActionPerformed
    /**
     * this button jobs:چون تعداد حالت نهایی نمی دانستیم ابتدا حالت نهایی را در اآرایه متغیر هاذخیره کردیم.
     * <br>  حال اینجا در مکان اصلی اش ذخیره می کنیم.وبه مرحله بعد می رویم.
     * @param evt
     */
    private void jbtnEndFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEndFinalActionPerformed

        if (f == 0) {
            StateFinal = new String[1];
            StateFinal[0] = "1";
        } else {
            StateFinal = new String[f];
        }

        for (int j = 0; j < f; j++) {
            StateFinal[j] = varible[j];
        }

        Draw jfDraw = new Draw(list, StateFinal);
        jfDraw.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtnEndFinalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                new FrameGrammers(selectedGR).setVisible(true);


            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxFinal;
    private javax.swing.JComboBox jComboBoxLeft;
    private javax.swing.JComboBox jComboBoxRight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnEG1;
    private javax.swing.JButton jbtnEndFinal;
    private javax.swing.JButton jbtnFinal;
    private javax.swing.JTextField jtxtAlpba;
    private javax.swing.JTextArea jtxtareaPrint;
    // End of variables declaration//GEN-END:variables
}
